financeApi:
  baseUrl: yfapi.net
  apiKey: 
database:
  mysql:
    host: localhost
    username: root
    password: xxx123
    db: master_stock
    timeout: 3
symbols:
  - KBANK.BK
  - EE.BK
  - GFPT.BK
  - LEE.BK
  - MAX.BK
  - NER.BK
  - PPPM.BK
  - STA.BK
  - TRUBB.BK
  - TWPC.BK
  - UPOIC.BK
  - UVAN.BK
  - VPO.BK
  - APURE.BK
  - ASIAN.BK
  - BR.BK
  - BRR.BK
  - CBG.BK
  - CFRESH.BK
  - CHOTI.BK
  - CM.BK
  - CPF.BK
  - CPI.BK
  - F&D.BK
  - HTC.BK
  - ICHI.BK
  - KBS.BK
  - KSL.BK
  - KTIS.BK
  - LST.BK
  - M.BK
  - MALEE.BK
  - MINT.BK
  - NRF.BK
  - OISHI.BK
  - OSP.BK
  - PB.BK
  - PM.BK
  - PRG.BK
  - RBF.BK
  - SAPPE.BK
  - SAUCE.BK
  - SFP.BK
  - SNP.BK
  - SORKON.BK
  - SSC.BK
  - SSF.BK
  - SST.BK
  - TC.BK
  - TFG.BK
  - TFMAMA.BK
  - TIPCO.BK
  - TKN.BK
  - TU.BK
  - TVO.BK
  - ZEN.BK
  - AFC.BK
  - B52.BK
  - BTNC.BK
  - CPH.BK
  - CPL.BK
  - ICC.BK
  - NC.BK
  - PAF.BK
  - PDJ.BK
  - PG.BK
  - SABINA.BK
  - SAWANG.BK
  - SUC.BK
  - TNL.BK
  - TPCORP.BK
  - TR.BK
  - TTI.BK
  - TTT.BK
  - UPF.BK
  - UT.BK
  - WACOAL.BK
  - ACC.BK
  - AJA.BK
  - DTCI.BK
  - FANCY.BK
  - KYE.BK
  - L&E.BK
  - MODERN.BK
  - OGC.BK
  - ROCK.BK
  - SIAM.BK
  - TSR.BK
  - APCO.BK
  - DDD.BK
  - JCT.BK
  - KISS.BK
  - OCC.BK
  - S&J.BK
  - STGT.BK
  - STHAI.BK
  - TNR.BK
  - TOG.BK
  - BAY.BK
  - BBL.BK
  - CIMBT.BK
  - KBANK.BK
  - KKP.BK
  - KTB.BK
  - LHFG.BK
  - SCB.BK
  - TCAP.BK
  - TISCO.BK
  - TMB.BK
  - AEC.BK
  - AEONTS.BK
  - AMANAH.BK
  - ASAP.BK
  - ASK.BK
  - ASP.BK
  - BAM.BK
  - BFIT.BK
  - CGH.BK
  - CHAYO.BK
  - ECL.BK
  - FNS.BK
  - FSS.BK
  - GBX.BK
  - GL.BK
  - IFS.BK
  - JMT.BK
  - KCAR.BK
  - KGI.BK
  - KTC.BK
  - MBKET.BK
  - MFC.BK
  - MICRO.BK
  - ML.BK
  - MTC.BK
  - NCAP.BK
  - PE.BK
  - PL.BK
  - S11.BK
  - SAK.BK
  - SAWAD.BK
  - THANI.BK
  - TK.BK
  - TNITY.BK
  - UOBKH.BK
  - ZMICO.BK
  - AYUD.BK
  - BKI.BK
  - BLA.BK
  - BUI.BK
  - CHARAN.BK
  - INSURE.BK
  - MTI.BK
  - NKI.BK
  - NSI.BK
  - SMK.BK
  - TGH.BK
  - THRE.BK
  - THREL.BK
  - TIP.BK
  - TQM.BK
  - TSI.BK
  - TVI.BK
  - 3K-BAT.BK
  - ACG.BK
  - AH.BK
  - CWT.BK
  - EASON.BK
  - GYT.BK
  - HFT.BK
  - IHL.BK
  - INGRS.BK
  - IRC.BK
  - PCSGH.BK
  - SAT.BK
  - SPG.BK
  - STANLY.BK
  - TKT.BK
  - TNPC.BK
  - TRU.BK
  - TSC.BK
  - ALLA.BK
  - ASEFA.BK
  - CPT.BK
  - CRANE.BK
  - CTW.BK
  - FMT.BK
  - HTECH.BK
  - KKC.BK
  - PK.BK
  - SNC.BK
  - STARK.BK
  - TCJ.BK
  - VARO.BK
  - UTP.BK
  - BCT.BK
  - CMAN.BK
  - GC.BK
  - GGC.BK
  - GIFT.BK
  - IVL.BK
  - NFC.BK
  - PATO.BK
  - PMTA.BK
  - PTTGC.BK
  - SUTHA.BK
  - TCCC.BK
  - TPA.BK
  - UAC.BK
  - UP.BK
  - VNT.BK
  - YCI.BK
  - AJ.BK
  - ALUCON.BK
  - BGC.BK
  - CSC.BK
  - GLOCON.BK
  - NEP.BK
  - PTL.BK
  - SCGP.BK
  - SFLEX.BK
  - SITHAI.BK
  - SLP.BK
  - SMPC.BK
  - SPACK.BK
  - TCOAT.BK
  - TFI.BK
  - THIP.BK
  - TMD.BK
  - TOPP.BK
  - TPBI.BK
  - TPP.BK
  - AMC.BK
  - BSBM.BK
  - CEN.BK
  - CITY.BK
  - CSP.BK
  - GJS.BK
  - GSTEEL.BK
  - INOX.BK
  - LHK.BK
  - MCS.BK
  - MILL.BK
  - NOVA.BK
  - PAP.BK
  - PERM.BK
  - SAM.BK
  - SMIT.BK
  - SSSC.BK
  - TGPRO.BK
  - THE.BK
  - TMT.BK
  - TSTH.BK
  - TWP.BK
  - TYCN.BK
  - CCP.BK
  - COTTO.BK
  - DCC.BK
  - DCON.BK
  - DRT.BK
  - EPG.BK
  - GEL.BK
  - PPP.BK
  - Q-CON.BK
  - RCI.BK
  - SCC.BK
  - SCCC.BK
  - SCP.BK
  - SKN.BK
  - TASCO.BK
  - TCMC.BK
  - TOA.BK
  - TPIPL.BK
  - UMI.BK
  - VNG.BK
  - WIIK.BK
  - A.BK
  - AMATA.BK
  - AMATAV.BK
  - ANAN.BK
  - AP.BK
  - APEX.BK
  - AQ.BK
  - AWC.BK
  - BLAND.BK
  - BROCK.BK
  - CGD.BK
  - CI.BK
  - CPN.BK
  - ESTAR.BK
  - EVER.BK
  - FPT.BK
  - GLAND.BK
  - J.BK
  - JCK.BK
  - KC.BK
  - KWG.BK
  - LALIN.BK
  - LH.BK
  - LPN.BK
  - MBK.BK
  - MJD.BK
  - MK.BK
  - NCH.BK
  - NNCL.BK
  - NOBLE.BK
  - NUSA.BK
  - NVD.BK
  - ORI.BK
  - PACE.BK
  - PF.BK
  - PLAT.BK
  - POLAR.BK
  - PRECHA.BK
  - PRIN.BK
  - PSH.BK
  - QH.BK
  - RICHY.BK
  - RML.BK
  - ROJNA.BK
  - S.BK
  - SA.BK
  - SAMCO.BK
  - SC.BK
  - SENA.BK
  - SF.BK
  - SIRI.BK
  - SPALI.BK
  - U.BK
  - UV.BK
  - WHA.BK
  - WIN.BK
  - AIMCG.BK
  - AIMIRT.BK
  - ALLY.BK
  - AMATAR.BK
  - B-WORK.BK
  - BKKCP.BK
  - BOFFICE.BK
  - CPNCG.BK
  - CPNREIT.BK
  - CPTGF.BK
  - CTARAF.BK
  - DREIT.BK
  - ERWPF.BK
  - FTREIT.BK
  - FUTUREPF.BK
  - GAHREIT.BK
  - GOLDPF.BK
  - GVREIT.BK
  - HPF.BK
  - HREIT.BK
  - IMPACT.BK
  - KPNPF.BK
  - LHHOTEL.BK
  - LHPF.BK
  - LHSC.BK
  - LPF.BK
  - LUXF.BK
  - M-II.BK
  - M-PAT.BK
  - M-STOR.BK
  - MIPF.BK
  - MIT.BK
  - MJLF.BK
  - MNIT.BK
  - MNIT2.BK
  - MNRF.BK
  - POPF.BK
  - PPF.BK
  - PROSPECT.BK
  - QHHR.BK
  - QHOP.BK
  - QHPF.BK
  - SBPF.BK
  - SHREIT.BK
  - SIRIP.BK
  - SPF.BK
  - SPRIME.BK
  - SRIPANWA.BK
  - SSPF.BK
  - SSTRT.BK
  - TIF1.BK
  - TLHPF.BK
  - TNPF.BK
  - TPRIME.BK
  - TTLPF.BK
  - TU-PF.BK
  - URBNPF.BK
  - WHABT.BK
  - WHART.BK
  - APCS.BK
  - BJCHI.BK
  - BKD.BK
  - CK.BK
  - CNT.BK
  - EMC.BK
  - ITD.BK
  - NWR.BK
  - PAE.BK
  - PLE.BK
  - PREB.BK
  - PYLON.BK
  - RT.BK
  - SEAFCO.BK
  - SQ.BK
  - SRICHA.BK
  - STEC.BK
  - STPI.BK
  - SYNTEC.BK
  - TEAMG.BK
  - TPOLY.BK
  - TRC.BK
  - TRITN.BK
  - TTCL.BK
  - UNIQ.BK
  - WGE.BK
  - 7UP.BK
  - ABPIF.BK
  - ACE.BK
  - AGE.BK
  - AI.BK
  - AKR.BK
  - BAFS.BK
  - BANPU.BK
  - BCP.BK
  - BCPG.BK
  - BGRIM.BK
  - BPP.BK
  - BRRGIF.BK
  - CKP.BK
  - DEMCO.BK
  - EA.BK
  - EASTW.BK
  - EGATIF.BK
  - EGCO.BK
  - EP.BK
  - ESSO.BK
  - ETC.BK
  - GPSC.BK
  - GREEN.BK
  - GULF.BK
  - GUNKUL.BK
  - IFEC.BK
  - IRPC.BK
  - KBSPIF.BK
  - LANNA.BK
  - MDX.BK
  - OR.BK
  - PDI.BK
  - PRIME.BK
  - PTG.BK
  - PTT.BK
  - PTTEP.BK
  - RATCH.BK
  - RPC.BK
  - SCG.BK
  - SCI.BK
  - SCN.BK
  - SGP.BK
  - SKE.BK
  - SOLAR.BK
  - SPCG.BK
  - SPRC.BK
  - SSP.BK
  - SUPER.BK
  - SUPEREIF.BK
  - SUSCO.BK
  - TAE.BK
  - TCC.BK
  - TOP.BK
  - TPIPP.BK
  - TSE.BK
  - TTW.BK
  - WHAUP.BK
  - WP.BK
  - THL.BK
  - BEAUTY.BK
  - BIG.BK
  - BJC.BK
  - COM7.BK
  - CPALL.BK
  - CPW.BK
  - CRC.BK
  - CSS.BK
  - DOHOME.BK
  - FN.BK
  - FTE.BK
  - GLOBAL.BK
  - HMPRO.BK
  - ILM.BK
  - IT.BK
  - KAMART.BK
  - LOXLEY.BK
  - MAKRO.BK
  - MC.BK
  - MEGA.BK
  - MIDA.BK
  - RS.BK
  - RSP.BK
  - SABUY.BK
  - SCM.BK
  - SINGER.BK
  - SPC.BK
  - SPI.BK
  - AHC.BK
  - BCH.BK
  - BDMS.BK
  - BH.BK
  - CHG.BK
  - CMR.BK
  - EKH.BK
  - KDH.BK
  - LPH.BK
  - M-CHAI.BK
  - NEW.BK
  - NTV.BK
  - PR9.BK
  - PRINC.BK
  - RAM.BK
  - RJH.BK
  - RPH.BK
  - SKR.BK
  - SVH.BK
  - THG.BK
  - VIBHA.BK
  - VIH.BK
  - WPH.BK
  - AMARIN.BK
  - AQUA.BK
  - AS.BK
  - BEC.BK
  - FE.BK
  - GPI.BK
  - GRAMMY.BK
  - JKN.BK
  - MACO.BK
  - MAJOR.BK
  - MATCH.BK
  - MATI.BK
  - MCOT.BK
  - MONO.BK
  - MPIC.BK
  - NMG.BK
  - PLANB.BK
  - POST.BK
  - PRAKIT.BK
  - SE-ED.BK
  - TBSP.BK
  - TH.BK
  - TKS.BK
  - VGI.BK
  - WAVE.BK
  - WORK.BK
  - BWG.BK
  - GENCO.BK
  - PRO.BK
  - SISB.BK
  - SO.BK
  - ASIA.BK
  - CENTEL.BK
  - CSR.BK
  - DTC.BK
  - ERW.BK
  - GRAND.BK
  - LRH.BK
  - MANRIN.BK
  - OHTL.BK
  - ROH.BK
  - SHANG.BK
  - SHR.BK
  - VRANDA.BK
  - AAV.BK
  - AOT.BK
  - ASIMAR.BK
  - B.BK
  - BA.BK
  - BEM.BK
  - BTS.BK
  - BTSGIF.BK
  - III.BK
  - JUTHA.BK
  - JWD.BK
  - KEX.BK
  - KWC.BK
  - NOK.BK
  - NYT.BK
  - PORT.BK
  - PRM.BK
  - PSL.BK
  - RCL.BK
  - TFFIF.BK
  - THAI.BK
  - TSTE.BK
  - TTA.BK
  - WICE.BK
  - CCET.BK
  - DELTA.BK
  - HANA.BK
  - KCE.BK
  - METCO.BK
  - NEX.BK
  - SMT.BK
  - SVI.BK
  - TEAM.BK
  - W.BK
  - ADVANC.BK
  - AIT.BK
  - ALT.BK
  - BLISS.BK
  - DIF.BK
  - DTAC.BK
  - FORTH.BK
  - HUMAN.BK
  - ILINK.BK
  - INET.BK
  - INTUCH.BK
  - JAS.BK
  - JASIF.BK
  - JMART.BK
  - JR.BK
  - JTS.BK
  - MFEC.BK
  - MSC.BK
  - PT.BK
  - SAMART.BK
  - SAMTEL.BK
  - SDC.BK
  - SIS.BK
  - SVOA.BK
  - SYMC.BK
  - SYNEX.BK
  - THCOM.BK
  - TRUE.BK
  - TWZ.BK